=== fsanperDev/desarrollo_aplicaciones_web/DAW/Lenguaje de marcas/Perez_Alvarez_Angela_LM04_Tarea/Actividad2/Act2.1.dtd
<!ELEMENT socios (socio)>
    <!ELEMENT socio (datos_personales|juego)*>

        <!ELEMENT datos_personales (cod_socio, nombre, apellidos, localidad, provincia, ((email)*| fecha_de_socio)*, (socio_vip)*)>
            <!ELEMENT cod_socio (#PCDATA)>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT apellidos (#PCDATA)>
            <!ELEMENT localidad (#PCDATA)>
            <!ELEMENT provincia (#PCDATA)>
            <!ELEMENT email (#PCDATA)>
            <!ELEMENT fecha_de_socio (#PCDATA)>
            <!ELEMENT socio_vip EMPTY>

        <!ELEMENT juego (nombre_juego, cod_juego, plataforma, estreno, adquisicion, estado, (online|multijugador)*)>
            <!ELEMENT nombre_juego (#PCDATA)>
            <!ELEMENT cod_juego (#PCDATA)>
            <!ELEMENT plataforma (#PCDATA)>
                <!ATTLIST plataforma plat (PC | XBOX | PS4 | WII ) "PC">
            <!ELEMENT estreno (#PCDATA)>
            <!ELEMENT adquisicion (#PCDATA)>
            <!ELEMENT estado (#PCDATA)>
            <!ELEMENT online EMPTY>
            <!ELEMENT multijugador EMPTY>

=== fsanperDev/desarrollo_aplicaciones_web/DAW/Lenguaje de marcas/Perez_Alvarez_Angela_LM04_Tarea/Actividad2/Act2.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE socios SYSTEM "Act2.1.dtd">
  <socios>
        <socio>
            <datos_personales>
                <cod_socio>SP-649</cod_socio>
                <nombre>Sara</nombre>
                <apellidos>Perez</apellidos>
                <localidad>Talavera de la Reina</localidad>
                <provincia>Toledo</provincia>
                <fecha_de_socio>13/9/2015</fecha_de_socio>
                <email>SP@gmail.com</email>
                <socio_vip></socio_vip>
            </datos_personales>
            <juego>
                <nombre_juego>Mario Kart 8</nombre_juego>
                <cod_juego>WII11</cod_juego>
                <plataforma plat='WII'>WII</plataforma>
                <estreno>2014</estreno>
                <adquisicion>1/2/2016</adquisicion>
                <estado>bueno</estado>
                <online></online>
            </juego>
            <juego>
                <nombre_juego>Far Cry 3</nombre_juego>
                <cod_juego>PS432</cod_juego>
                <plataforma plat='PS4'>PS4</plataforma>
                <estreno>16/10/2009</estreno>
                <adquisicion>08/3/2016</adquisicion>
                <estado>bueno</estado>
                <multijugador></multijugador>
            </juego>
            <juego>
                <nombre_juego>Fable III</nombre_juego>
                <cod_juego>XBOX13</cod_juego>
                <plataforma plat='XBOX'>XBOX</plataforma>
                <estreno>27/11/2013</estreno>
                <adquisicion>09/09/2016</adquisicion>
                <estado>bueno</estado>
                <online></online>
                <multijugador></multijugador>
            </juego>
        </socio>
 </socios>
