=== fsanperDev/desarrollo_aplicaciones_web/DAW/Lenguaje de marcas/Perez_Alvarez_Angela_LM04_Tarea/Actividad3/Act3.1.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

<!-- elementos simples -->
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="apellidos" type="xs:string"/>
    <xs:element name="localidad" type="xs:string"/>
    <xs:element name="provincia" type="xs:string"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="fecha_de_socio" type="xs:date"/>
    <xs:element name="socio_vip"/>
    <xs:element name="nombre_juego" type="xs:string"/>
    <xs:element name="estreno" type="xs:gYear"/>
    <xs:element name="adquisicion" type="xs:date"/>
    <xs:element name="estado" type="xs:string" default="bueno"/>
    <xs:element name="online"/>
    <xs:element name="multijugador"/>
    
<!--atributos -->
    <xs:element name="cod_socio">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[A-Z]{2}-[0-9]{3}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="cod_juego">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[WII-XBOX-PS4-PC]\d{2}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="plataforma">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[WII-XBOX-PS4-PC]"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
<!-- elementos complejos -->    
    <xs:element name="datos_personales">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cod_socio"/>
                <xs:element ref="nombre"/>
                <xs:element ref="apellidos"/>
                <xs:element ref="localidad"/>
                <xs:element ref="provincia"/>
                <xs:choice>
                    <xs:sequence>
                        <xs:element ref="email" maxOccurs="2"/>
                        <xs:element ref="fecha_de_socio"/>
                    </xs:sequence>
                    <xs:sequence>
                        <xs:element ref="fecha_de_socio"/>
                        <xs:element ref="email" maxOccurs="2"/>
                    </xs:sequence>
                </xs:choice>
                <xs:element ref="socio_vip" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>  
    </xs:element>
    
    <xs:element name="juego">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre_juego"/>
                <xs:element ref="cod_juego"/>
                <xs:element ref="plataforma"/>
                <xs:element ref="estreno"/>
                <xs:element ref="adquisicion"/>
                <xs:element ref="estado"/>
                <xs:choice>
                    <xs:sequence>
                        <xs:element ref="online" minOccurs="0" maxOccurs="1"/>
                        <xs:element ref="multijugador" minOccurs="0" maxOccurs="1"/>
                    </xs:sequence>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element> 

    <xs:element name="socio">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="datos_personales"/>
                <xs:element ref="juego"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="socios">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="socio"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- elementos raiz -->
    <xs:element name="info">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="socios"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== fsanperDev/desarrollo_aplicaciones_web/DAW/Lenguaje de marcas/Perez_Alvarez_Angela_LM04_Tarea/Actividad3/Act3.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<info xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Act3.1.xsd' >
    <socios>
        <socio>
            <datos_personales>
                <cod_socio>SP-649</cod_socio>
                <nombre>Sara</nombre>
                <apellidos>Perez</apellidos>
                <localidad>Talavera de la Reina</localidad>
                <provincia>Toledo</provincia>
                <fecha_de_socio>2015-09-13</fecha_de_socio>
                <email>SP@gmail.com</email>
                <socio_vip></socio_vip>
            </datos_personales>
            <juego>
                <nombre_juego>Mario Kart 8</nombre_juego>
                <cod_juego>WII11</cod_juego>
                <plataforma>WII</plataforma>
                <estreno>2014</estreno>
                <adquisicion>2016-02-01</adquisicion>
                <estado>bueno</estado>
                <online></online>
            </juego>
            <juego>
                <nombre_juego>Far Cry 3</nombre_juego>
                <cod_juego>PS432</cod_juego>
                <plataforma>PS4</plataforma>
                <estreno>2009</estreno>
                <adquisicion>2016-03-08</adquisicion>
                <estado></estado>
                <multijugador></multijugador>
            </juego>
            <juego>
                <nombre_juego>Fable III</nombre_juego>
                <cod_juego>XBOX13</cod_juego>
                <plataforma>XBOX</plataforma>
                <estreno>2013</estreno>
                <adquisicion>2016-09-09</adquisicion>
                <estado></estado>
                <online></online>
                <multijugador></multijugador>
            </juego>
        </socio>
    </socios>
</info>

=== fsanperDev/desarrollo_aplicaciones_web/DAW/Lenguaje de marcas/Perez_Alvarez_Angela_LM04_Tarea/Actividad3/Act3.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<info xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Act3.1.xsd' >
    <socios>
        <socio>
            <datos_personales>
                <cod_socio>AB-123</cod_socio>
                <nombre>Alberto</nombre>
                <apellidos>Gomez</apellidos>
                <localidad>Alcala de Henares</localidad>
                <provincia>Madrid</provincia>
                <email>AG@gmail.com</email>
                <email>AlGomez@gmail.com</email>
                <fecha_de_socio>2017-04-14</fecha_de_socio>
            </datos_personales>
            <juego>
                <nombre_juego>The elder Scrol V: Skyrim</nombre_juego>
                <cod_juego>PC05</cod_juego>
                <plataforma>PC</plataforma>
                <estreno>2011</estreno>
                <adquisicion>2017-04-16</adquisicion>
                <estado></estado>
            </juego>
            <juego>
                <nombre_juego>Blodborn</nombre_juego>
                <cod_juego>PS466</cod_juego>
                <plataforma>PS4</plataforma>
                <estreno>2015</estreno>
                <adquisicion>2017-06-23</adquisicion>
                <estado></estado>
                <online></online>
                <multijugador></multijugador>
            </juego>
            <juego>
                <nombre_juego>Halo Guardians</nombre_juego>
                <cod_juego>XBOX05</cod_juego>
                <plataforma>XBOX</plataforma>
                <estreno>2015</estreno>
                <adquisicion>2017-12-06</adquisicion>
                <estado></estado>
                <online></online>
                <multijugador></multijugador>
            </juego>
        </socio>
    </socios>
</info>
